CC = gcc


CFLAGS = -Wall -pedantic -ansi 
-ls

OUTPUT = main



all: main simplecalc supercalc numeric graphic
	$(CC) $(CFLAGS) -o $(OUTPUT) *o
main:
	
	$(CC) $(CFLAGS) -c -o -lm main.o main.c

supercalc:
	
	$(CC) $(CFLAGS) -c -o -lm supercalc.o supercalc.c
simplecalc:
	
	$(CC) $(CFLAGS) -c -o -lm simplecalc.o simplecalc.c

numeric:
	
	$(CC) $(CFLAGS) -c -o -lm numeric.o numeric.c

graphic:
	
	$(CC) $(CFLAGS) -c -o -lm graphic.o graphic.c

clean:
	rm -rf *.o & rm $(OUTPUT)
